### ISSUE TITLE
Feature list*

### ISSUE THREAD

**Issue by unckleg** [tasmaniski/unfinished#141]
Consider:
- Using DataTable for listing records (Page, Article's, Categories...) 
- Move delete/status buttons from Edit to Index actions to be in table next to edit button.
- Exception collecting and revealing them on the template as some kind of notification.
- Adding global config module for Global site SEO meta data (title, desc, image, og:img....)
- Adding default seo input fields in modules that are exposed directly on Front. 
- If it is considered at all for website to be multilang at some point. In that case it is necessary to change the logic immediately because there is not much content yet and to continue developing this way. The **juniors** and **everyone who contributes** will be able to learn a lot through a multilang system that I believe each of us regularly meets **And** also the content on front 'll be much organized, transparent because it is now linguistically mixed.

That's it for now :)

**Comment by tasmaniski** [comment]
> Using DataTable for listing records (Page, Article's, Categories...)

Can you please check **Page** package and explain what you mean by "Using DataTable"?

> Move delete/status buttons from Edit to Index actions to be in table next to edit button.
> Exception collecting and revealing them on the template as some kind of notification.

We try to focus on "bigger" things. This change wouldn't bring anything crucial.

> Adding global config module for Global site SEO meta data (title, desc, image, og:img....)
> Adding default seo input fields in modules that are exposed directly on Front.

This PR would be great! :) 
It's should goes in new package eg. **Settings** package where we can set global config for the  website - SEO tags, GA code, etc.

> The last one

We are focusing on big things, but this one would be too big for now. 
Sure, there is a disadvantage if we do not implement it now. 
But that would give us lot more opportunity to change architecture and "break a things" before we got stable product. Also, There are many questions like should we translate only interface or content or Both? Also there is different between localization and translating... 
I suggest that we talk about this topic later.

**Comment by tasmaniski** [comment]
Please check the Road Map  https://github.com/phpsrbija/unfinished/blob/master/README.md
