### ISSUE TITLE
[BUG] Rehydration of Page entity without id.

### ISSUE THREAD

**Issue by unckleg** [tasmaniski/unfinished#144]
FP: _**Pacages\Page\Controller\PageController**_
```
....
public function edit($errors = []): HtmlResponse
{
        $id = $this->request->getAttribute('id');
        $page = $this->pageService->getPage($id);
        if ($this->request->getParsedBody()) {
            $page = new \Page\Entity\Page();
            $page->exchangeArray($this->request->getParsedBody() + (array) $page);
        }
}
```

Here: `$page->exchangeArray($this->request->getParsedBody() + (array) $page);`
ID of page is not part of Parsedbody so you will not hydrate page_id property of Page Entity class.
And if there where some errors as part of response you will get bad form action URL.

**Comment by tasmaniski** [comment]
Confirmed. 

Merged with #145
