### ISSUE TITLE
Centralize strict type declaration

### ISSUE THREAD

**Issue by vladapopster** [tasmaniski/unfinished#31]
Move `declare(strict_types = 1);` to single point.
Maybe to `index.php`?

**Comment by tasmaniski** [comment]
ping @digitronac

**Comment by digitronac** [comment]
strict_types declaration can only be set on per file basis

**Comment by tasmaniski** [comment]
You can check https://www.sitepoint.com/community/t/php7-strict-mode-globally/191403/1 
there is a good point why there is no global way to set strict types. 
Probably in the future there will be a way...

**Comment by vladapopster** [comment]
I hope so, as very soon almost all php files in business domain will start with `<?php
declare(strict_types = 1);` instead of `<?php`.
